"""Build the runtime character atlas from the editable per-frame PNG sources."""

from __future__ import annotations

import json
import math
from pathlib import Path

from PIL import Image


SCRIPT_DIRECTORY = Path(__file__).resolve().parent
CLIENT_DIRECTORY = SCRIPT_DIRECTORY.parent
ASSET_DIRECTORY = CLIENT_DIRECTORY / "public" / "assets"
ATLAS_DIRECTORY = ASSET_DIRECTORY / "characters"
ATLAS_PATH = ATLAS_DIRECTORY / "character_spritesheet.png"
MANIFEST_PATH = CLIENT_DIRECTORY / "src" / "assets" / "characterAtlasManifest.ts"

CELL_WIDTH = 52
CELL_HEIGHT = 54
COLUMNS = 19
SQUAD_COLORS = ("blue", "green", "yellow")

CHARACTERS = (
    {
        "id": "female1",
        "displayName": "Female1",
        "sourceId": "lenne",
        "lyingFrame": 51,
        "hasDefaultAssets": False,
    },
    {
        "id": "male1",
        "displayName": "Male1",
        "sourceId": "glenn",
        "lyingFrame": 55,
        "hasDefaultAssets": False,
    },
    {
        "id": "female2",
        "displayName": "Female2",
        "sourceId": "amalia",
        "lyingFrame": 48,
        "hasDefaultAssets": False,
    },
    {
        "id": "male2",
        "displayName": "Male2",
        "sourceId": "robb",
        "lyingFrame": 55,
        "hasDefaultAssets": True,
    },
    {
        "id": "female3",
        "displayName": "Female3",
        "sourceId": "sienna",
        "lyingFrame": 50,
        "hasDefaultAssets": True,
    },
)


def frame_numbers(lying_frame: int) -> list[int]:
    return [0, 1, 2, 3, 4, *range(16, 46), lying_frame]


def variant_directory(character: dict[str, object], squad_color: str | None) -> Path:
    source_id = str(character["sourceId"])
    root = ASSET_DIRECTORY / source_id
    return root if squad_color is None else root / f"{source_id}_{squad_color}"


def source_frame_path(
    character: dict[str, object], squad_color: str | None, frame_number: int
) -> Path:
    source_id = str(character["sourceId"])
    return variant_directory(character, squad_color) / f"{source_id}_{frame_number}.png"


def runtime_sets() -> list[tuple[dict[str, object], str | None]]:
    sets: list[tuple[dict[str, object], str | None]] = []
    for character in CHARACTERS:
        if bool(character["hasDefaultAssets"]):
            sets.append((character, None))
        sets.extend((character, color) for color in SQUAD_COLORS)
    return sets


def build_atlas() -> None:
    sets = runtime_sets()
    frame_count = sum(len(frame_numbers(int(character["lyingFrame"]))) for character, _ in sets)
    rows = math.ceil(frame_count / COLUMNS)
    atlas = Image.new("RGBA", (COLUMNS * CELL_WIDTH, rows * CELL_HEIGHT), (0, 0, 0, 0))
    manifest_by_id: dict[str, dict[str, object]] = {
        str(character["id"]): {
            "id": character["id"],
            "displayName": character["displayName"],
            "defaultFrames": None,
            "squadFrames": {},
        }
        for character in CHARACTERS
    }

    atlas_index = 0
    for character, squad_color in sets:
        frames: list[list[int]] = []
        for frame_number in frame_numbers(int(character["lyingFrame"])):
            path = source_frame_path(character, squad_color, frame_number)
            if not path.is_file():
                raise FileNotFoundError(f"Missing character frame: {path}")

            with Image.open(path) as source:
                frame = source.convert("RGBA")
                if frame.width > CELL_WIDTH - 2 or frame.height > CELL_HEIGHT - 2:
                    raise ValueError(
                        f"Frame {path} is {frame.width}x{frame.height}; "
                        f"atlas cells support at most {CELL_WIDTH - 2}x{CELL_HEIGHT - 2}"
                    )

                column = atlas_index % COLUMNS
                row = atlas_index // COLUMNS
                x = column * CELL_WIDTH + 1
                y = row * CELL_HEIGHT + 1
                atlas.alpha_composite(frame, (x, y))
                frames.append([frame_number, x, y, frame.width, frame.height])
                atlas_index += 1

        target = manifest_by_id[str(character["id"])]
        if squad_color is None:
            target["defaultFrames"] = frames
        else:
            squad_frames = target["squadFrames"]
            assert isinstance(squad_frames, dict)
            squad_frames[squad_color] = frames

    ATLAS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    atlas.save(ATLAS_PATH, format="PNG", optimize=True, compress_level=9)

    manifest_json = json.dumps(list(manifest_by_id.values()), indent=2)
    manifest_source = f"""// Generated by scripts/build-character-atlas.py. Do not edit by hand.

export const CHARACTER_ATLAS_PATH = 'assets/characters/character_spritesheet.png';

export const CHARACTER_ATLAS_MANIFEST = {manifest_json} as const;
"""
    MANIFEST_PATH.write_text(manifest_source, encoding="utf-8", newline="\n")

    print(
        f"Built {ATLAS_PATH} ({atlas.width}x{atlas.height}) with "
        f"{len(sets)} animation sets and {atlas_index} frames"
    )


if __name__ == "__main__":
    build_atlas()
