import { getFiorwoodsRuntimeAssetPath } from '../assets/runtimeAssetPaths';

export type TIntersectionDecorationAsset =
  keyof typeof T_INTERSECTION_DECORATION_ASSET_PATH_BY_ID;

export interface TIntersectionDecorationSpriteSpec {
  asset: TIntersectionDecorationAsset;
  name: string;
  nativeWidth: number;
  nativeHeight: number;
  x: number;
  y: number;
  w: number;
  h: number;
  z: number;
  role: 'ground.grass' | 'decoration' | 'bush';
  layer: 'ground' | 'entity';
  entityGroup?: 'signpost';
}

const ROOT = '/assets/t-intersection-decoration';

const T_INTERSECTION_DECORATION_ASSET_PATH_BY_ID = {
  a154: `${ROOT}/Sprite_Ancient_Ruins_154.png`,
  a156: `${ROOT}/Sprite_Ancient_Ruins_156.png`,
  a157: `${ROOT}/Sprite_Ancient_Ruins_157.png`,
  a204: `${ROOT}/Sprite_Ancient_Ruins_204.png`,
  a205: `${ROOT}/Sprite_Ancient_Ruins_205.png`,
  a206: `${ROOT}/Sprite_Ancient_Ruins_206.png`,
  a207: `${ROOT}/Sprite_Ancient_Ruins_207.png`,
  a208: `${ROOT}/Sprite_Ancient_Ruins_208.png`,
  r350: `${ROOT}/Sprite_Rohlan_Fields_350.png`,
  r399: `${ROOT}/Sprite_Rohlan_Fields_399.png`,
  r400: `${ROOT}/Sprite_Rohlan_Fields_400.png`,
  r450: `${ROOT}/Sprite_Rohlan_Fields_450.png`,
  bush: `${ROOT}/bush01.png`,
  bush4: `${ROOT}/bush04.png`,
  f1285: getFiorwoodsRuntimeAssetPath(1285),
  goldflowers3: `${ROOT}/goldflowers_3.png`,
  goldflowers9: `${ROOT}/goldflowers_9.png`,
} as const;

/** Exact expanded north-closed T-junction composition exported from style editor (16). */
export const T_INTERSECTION_DECORATION_SPRITES: readonly TIntersectionDecorationSpriteSpec[] =
  [
    {
      asset: 'r450',
      name: 'Sprite_Rohlan Fields_450',
      nativeWidth: 22,
      nativeHeight: 32,
      x: 66,
      y: 16,
      w: 11,
      h: 16,
      z: 107108,
      role: 'ground.grass',
      layer: 'entity',
      entityGroup: 'signpost',
    },
    {
      asset: 'r400',
      name: 'Sprite_Rohlan Fields_400',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 61,
      y: 0,
      w: 16,
      h: 16,
      z: 107108,
      role: 'ground.grass',
      layer: 'entity',
      entityGroup: 'signpost',
    },
    {
      asset: 'r350',
      name: 'Sprite_Rohlan Fields_350',
      nativeWidth: 28,
      nativeHeight: 15,
      x: 62,
      y: -7,
      w: 14,
      h: 7,
      z: 106108,
      role: 'ground.grass',
      layer: 'entity',
      entityGroup: 'signpost',
    },
    {
      asset: 'a207',
      name: 'Sprite_Ancient Ruins_207',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 32,
      y: 80,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a206',
      name: 'Sprite_Ancient Ruins_206',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 48,
      y: 80,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a154',
      name: 'Sprite_Ancient Ruins_154',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 32,
      y: 64,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a204',
      name: 'Sprite_Ancient Ruins_204',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 48,
      y: 64,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a156',
      name: 'Sprite_Ancient Ruins_156',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 32,
      y: 48,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a157',
      name: 'Sprite_Ancient Ruins_157',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 48,
      y: 48,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a154',
      name: 'Sprite_Ancient Ruins_154',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 32,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a204',
      name: 'Sprite_Ancient Ruins_204',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 48,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a207',
      name: 'Sprite_Ancient Ruins_207',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 64,
      y: 48,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a154',
      name: 'Sprite_Ancient Ruins_154',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 64,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a205',
      name: 'Sprite_Ancient Ruins_205',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 80,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a207',
      name: 'Sprite_Ancient Ruins_207',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 0,
      y: 48,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a204',
      name: 'Sprite_Ancient Ruins_204',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 16,
      y: 48,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a154',
      name: 'Sprite_Ancient Ruins_154',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 0,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'a205',
      name: 'Sprite_Ancient Ruins_205',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 16,
      y: 32,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'bush',
      name: 'bush01',
      nativeWidth: 44,
      nativeHeight: 46,
      x: 44,
      y: 9,
      w: 22,
      h: 23,
      z: 2,
      role: 'bush',
      layer: 'entity',
    },
    {
      asset: 'a157',
      name: 'Sprite_Ancient Ruins_157',
      nativeWidth: 32,
      nativeHeight: 32,
      x: 1,
      y: 16,
      w: 16,
      h: 16,
      z: 1,
      role: 'decoration',
      layer: 'ground',
    },
    {
      asset: 'r399',
      name: 'Sprite_Rohlan Fields_399',
      nativeWidth: 32,
      nativeHeight: 31,
      x: 64,
      y: 64,
      w: 16,
      h: 16,
      z: 1,
      role: 'ground.grass',
      layer: 'ground',
    },
    {
      asset: 'goldflowers3',
      name: 'goldflowers_3',
      nativeWidth: 23,
      nativeHeight: 24,
      x: 63,
      y: 74,
      w: 12,
      h: 12,
      z: 2,
      role: 'bush',
      layer: 'ground',
    },
    {
      asset: 'goldflowers9',
      name: 'goldflowers_9',
      nativeWidth: 31,
      nativeHeight: 13,
      x: 51,
      y: 25,
      w: 16,
      h: 7,
      z: 500,
      role: 'bush',
      layer: 'entity',
    },
    {
      asset: 'goldflowers3',
      name: 'goldflowers_3',
      nativeWidth: 23,
      nativeHeight: 24,
      x: 22,
      y: 57,
      w: 12,
      h: 12,
      z: 2,
      role: 'bush',
      layer: 'ground',
    },
    {
      asset: 'r399',
      name: 'Sprite_Rohlan Fields_399',
      nativeWidth: 32,
      nativeHeight: 31,
      x: 33,
      y: 17,
      w: 16,
      h: 16,
      z: 1,
      role: 'ground.grass',
      layer: 'ground',
    },
    {
      asset: 'goldflowers3',
      name: 'goldflowers_3',
      nativeWidth: 23,
      nativeHeight: 24,
      x: 23,
      y: 15,
      w: 12,
      h: 12,
      z: 2,
      role: 'bush',
      layer: 'ground',
    },
    {
      asset: 'goldflowers9',
      name: 'goldflowers_9',
      nativeWidth: 31,
      nativeHeight: 13,
      x: 13,
      y: 67,
      w: 16,
      h: 7,
      z: 500,
      role: 'bush',
      layer: 'entity',
    },
    {
      asset: 'goldflowers3',
      name: 'goldflowers_3',
      nativeWidth: 23,
      nativeHeight: 24,
      x: 82,
      y: 58,
      w: 12,
      h: 12,
      z: 2,
      role: 'bush',
      layer: 'ground',
    },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 32, y: 128, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a206', name: 'Sprite_Ancient Ruins_206', nativeWidth: 32, nativeHeight: 32, x: 48, y: 128, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 32, y: 112, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: 48, y: 112, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a156', name: 'Sprite_Ancient Ruins_156', nativeWidth: 32, nativeHeight: 32, x: 32, y: 96, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 48, y: 96, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 32, y: 176, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 32, y: 160, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: 48, y: 160, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a156', name: 'Sprite_Ancient Ruins_156', nativeWidth: 32, nativeHeight: 32, x: 32, y: 144, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a205', name: 'Sprite_Ancient Ruins_205', nativeWidth: 32, nativeHeight: 32, x: 48, y: 144, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a156', name: 'Sprite_Ancient Ruins_156', nativeWidth: 32, nativeHeight: 32, x: 128, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a208', name: 'Sprite_Ancient Ruins_208', nativeWidth: 32, nativeHeight: 18, x: 144, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 128, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: 144, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 160, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 160, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a205', name: 'Sprite_Ancient Ruins_205', nativeWidth: 32, nativeHeight: 32, x: 176, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 96, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: 112, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: 96, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a206', name: 'Sprite_Ancient Ruins_206', nativeWidth: 32, nativeHeight: 32, x: 112, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a156', name: 'Sprite_Ancient Ruins_156', nativeWidth: 32, nativeHeight: 32, x: -64, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a157', name: 'Sprite_Ancient Ruins_157', nativeWidth: 32, nativeHeight: 32, x: -48, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: -64, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: -48, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: -32, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: -32, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a205', name: 'Sprite_Ancient Ruins_205', nativeWidth: 32, nativeHeight: 32, x: -16, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: -96, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a204', name: 'Sprite_Ancient Ruins_204', nativeWidth: 32, nativeHeight: 32, x: -80, y: 48, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a154', name: 'Sprite_Ancient Ruins_154', nativeWidth: 32, nativeHeight: 32, x: -96, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a205', name: 'Sprite_Ancient Ruins_205', nativeWidth: 32, nativeHeight: 32, x: -80, y: 32, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a157', name: 'Sprite_Ancient Ruins_157', nativeWidth: 32, nativeHeight: 32, x: -64, y: 64, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 128, y: 64, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'a207', name: 'Sprite_Ancient Ruins_207', nativeWidth: 32, nativeHeight: 32, x: 160, y: 16, w: 16, h: 16, z: 1, role: 'decoration', layer: 'ground' },
    { asset: 'bush', name: 'bush01', nativeWidth: 44, nativeHeight: 46, x: 143, y: 64, w: 22, h: 23, z: 2, role: 'bush', layer: 'entity' },
    { asset: 'goldflowers9', name: 'goldflowers_9', nativeWidth: 31, nativeHeight: 13, x: 128, y: 77, w: 16, h: 7, z: 500, role: 'bush', layer: 'entity' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: 168, y: 66, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'bush4', name: 'bush04', nativeWidth: 48, nativeHeight: 40, x: -48, y: 63, w: 24, h: 20, z: 2, role: 'bush', layer: 'entity' },
    { asset: 'bush', name: 'bush01', nativeWidth: 44, nativeHeight: 46, x: -71, y: 2, w: 22, h: 23, z: 2, role: 'bush', layer: 'entity' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: -51, y: 11, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'r399', name: 'Sprite_Rohlan Fields_399', nativeWidth: 32, nativeHeight: 31, x: 128, y: 16, w: 16, h: 16, z: 1, role: 'ground.grass', layer: 'ground' },
    { asset: 'r399', name: 'Sprite_Rohlan Fields_399', nativeWidth: 32, nativeHeight: 31, x: 144, y: 16, w: 16, h: 16, z: 1, role: 'ground.grass', layer: 'ground' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: 137, y: 5, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'f1285', name: 'Sprite_Fiorwoods_1285', nativeWidth: 31, nativeHeight: 29, x: 68, y: 112, w: 16, h: 15, z: 2, role: 'ground.grass', layer: 'entity' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: 63, y: 105, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'bush4', name: 'bush04', nativeWidth: 48, nativeHeight: 40, x: 8, y: 138, w: 24, h: 20, z: 2, role: 'bush', layer: 'entity' },
    { asset: 'goldflowers9', name: 'goldflowers_9', nativeWidth: 31, nativeHeight: 13, x: 15, y: 152, w: 16, h: 7, z: 500, role: 'bush', layer: 'entity' },
    { asset: 'r399', name: 'Sprite_Rohlan Fields_399', nativeWidth: 32, nativeHeight: 31, x: 16, y: 128, w: 16, h: 16, z: 1, role: 'ground.grass', layer: 'ground' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: 9, y: 103, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'goldflowers3', name: 'goldflowers_3', nativeWidth: 23, nativeHeight: 24, x: 91, y: 11, w: 12, h: 12, z: 2, role: 'bush', layer: 'ground' },
    { asset: 'goldflowers9', name: 'goldflowers_9', nativeWidth: 31, nativeHeight: 13, x: 95, y: 20, w: 16, h: 7, z: 500, role: 'bush', layer: 'entity' },
    { asset: 'goldflowers9', name: 'goldflowers_9', nativeWidth: 31, nativeHeight: 13, x: 70, y: 120, w: 16, h: 7, z: 500, role: 'bush', layer: 'entity' },
  ];

export function getTIntersectionDecorationAssetPath(
  asset: TIntersectionDecorationAsset,
): string {
  return T_INTERSECTION_DECORATION_ASSET_PATH_BY_ID[asset];
}

export const T_INTERSECTION_DECORATION_ASSET_PATHS = [
  ...new Set(Object.values(T_INTERSECTION_DECORATION_ASSET_PATH_BY_ID)),
];
