// Generated by scripts/build-runtime-atlas.py. Do not edit by hand.

export const RUNTIME_ATLAS_PATH = 'assets/runtime/runtime-atlas.png';
export const RUNTIME_ATLAS_WIDTH = 1088;
export const RUNTIME_ATLAS_HEIGHT = 640;
export const RUNTIME_ATLAS_SOURCE_DIGEST = '2dbfdad9246cdfe7790311456836cb96c3199f237bb1b587767ca81ff4891b57';
export const RUNTIME_ATLAS_PNG_DIGEST = 'e2004083a40a2a7f580dd48b1094afafdc8c25c7ec0e9569b0c182c2a6824f17';

export const RUNTIME_ATLAS_FRAMES = {
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_105.png": [
    446,
    167,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_106.png": [
    478,
    203,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_106_front.png": [
    278,
    124,
    32,
    10
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_106_front_shadow.png": [
    981,
    495,
    32,
    10
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_107.png": [
    482,
    167,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_108.png": [
    395,
    566,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_109.png": [
    395,
    602,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_110.png": [
    495,
    76,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_819.png": [
    495,
    112,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_820.png": [
    520,
    2,
    32,
    32
  ],
  "assets/bridge-obstacle/Sprite_Ancient_Ruins_821.png": [
    520,
    38,
    32,
    32
  ],
  "assets/bridge-obstacle/burriedTreasureCircle.png": [
    427,
    466,
    32,
    32
  ],
  "assets/bridge-obstacle/watergrass_3.png": [
    1011,
    254,
    31,
    32
  ],
  "assets/bridge-obstacle/watergrass_6.png": [
    827,
    586,
    25,
    23
  ],
  "assets/cage/birdCage1.png": [
    355,
    351,
    20,
    32
  ],
  "assets/cage/birdCage2.png": [
    1018,
    426,
    20,
    32
  ],
  "assets/cage/birdCage3.png": [
    1042,
    426,
    20,
    32
  ],
  "assets/chest-dead-end/chest01_0.png": [
    977,
    526,
    30,
    25
  ],
  "assets/chest-dead-end/chest01_16.png": [
    454,
    239,
    30,
    37
  ],
  "assets/chest-dead-end/goldflowers_9.png": [
    977,
    509,
    31,
    13
  ],
  "assets/contract_button.png": [
    907,
    614,
    18,
    18
  ],
  "assets/expand_button.png": [
    929,
    614,
    18,
    18
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_102.png": [
    433,
    403,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1030.png": [
    427,
    502,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1031.png": [
    457,
    335,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1032.png": [
    471,
    280,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1033.png": [
    1005,
    432,
    9,
    21
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1046.png": [
    1077,
    462,
    9,
    21
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1047.png": [
    488,
    239,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1048.png": [
    514,
    203,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1049.png": [
    518,
    148,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_105.png": [
    531,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_108.png": [
    531,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1080.png": [
    945,
    484,
    32,
    11
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1081.png": [
    1017,
    494,
    32,
    11
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1082.png": [
    1017,
    479,
    17,
    11
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1089.png": [
    219,
    626,
    32,
    12
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_110.png": [
    556,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1102.png": [
    556,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1103.png": [
    431,
    538,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1104.png": [
    431,
    574,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1105.png": [
    463,
    439,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1106.png": [
    463,
    475,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1109.png": [
    469,
    371,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1110.png": [
    493,
    316,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1111.png": [
    507,
    275,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1112.png": [
    524,
    239,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1114.png": [
    550,
    184,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1131.png": [
    882,
    610,
    21,
    19
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1152.png": [
    554,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1154.png": [
    567,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1155.png": [
    567,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1156.png": [
    592,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1158.png": [
    592,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1159.png": [
    467,
    511,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1161.png": [
    467,
    547,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1162.png": [
    467,
    583,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1164.png": [
    499,
    407,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1181.png": [
    505,
    352,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1202.png": [
    529,
    311,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1203.png": [
    543,
    275,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1206.png": [
    560,
    220,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1207.png": [
    586,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1209.png": [
    590,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1210.png": [
    499,
    443,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1211.png": [
    603,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1212.png": [
    603,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1213.png": [
    628,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1214.png": [
    628,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1231.png": [
    503,
    479,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1232.png": [
    535,
    388,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1281.png": [
    541,
    347,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1282.png": [
    565,
    311,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1284.png": [
    961,
    290,
    32,
    30
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1285.png": [
    1053,
    508,
    31,
    29
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1286.png": [
    579,
    256,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1290.png": [
    596,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1291.png": [
    622,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_138.png": [
    626,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_139.png": [
    535,
    424,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_140.png": [
    639,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_141.png": [
    639,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_142.png": [
    664,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_143.png": [
    664,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1437.png": [
    327,
    610,
    32,
    26
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1443.png": [
    865,
    361,
    32,
    26
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1446.png": [
    901,
    361,
    32,
    26
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1447.png": [
    859,
    421,
    32,
    25
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1485.png": [
    503,
    515,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1537.png": [
    579,
    292,
    18,
    15
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_154.png": [
    503,
    551,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1542.png": [
    471,
    316,
    18,
    15
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1545.png": [
    503,
    587,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_155.png": [
    539,
    460,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1577.png": [
    909,
    567,
    20,
    17
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1578.png": [
    884,
    485,
    32,
    17
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1579.png": [
    1053,
    494,
    32,
    10
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1580.png": [
    503,
    623,
    32,
    14
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1581.png": [
    314,
    124,
    27,
    10
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1587.png": [
    571,
    383,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1591.png": [
    791,
    614,
    32,
    13
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1592.png": [
    577,
    347,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_160.png": [
    556,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1627.png": [
    953,
    534,
    20,
    27
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1628.png": [
    997,
    290,
    32,
    30
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1629.png": [
    571,
    419,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1630.png": [
    1033,
    290,
    32,
    30
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1631.png": [
    920,
    534,
    29,
    29
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_164.png": [
    601,
    292,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_165.png": [
    615,
    254,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_166.png": [
    632,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1677.png": [
    856,
    586,
    24,
    20
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1678.png": [
    931,
    588,
    17,
    18
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1727.png": [
    889,
    325,
    29,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1728.png": [
    1066,
    426,
    19,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1777.png": [
    922,
    325,
    29,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1778.png": [
    1046,
    254,
    31,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1827.png": [
    847,
    522,
    25,
    29
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1828.png": [
    658,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_188.png": [
    662,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_189.png": [
    675,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_190.png": [
    675,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_191.png": [
    700,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_192.png": [
    700,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_193.png": [
    539,
    496,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1987.png": [
    539,
    532,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1988.png": [
    539,
    568,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_1992.png": [
    539,
    604,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_238.png": [
    575,
    455,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_239.png": [
    607,
    383,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_240.png": [
    607,
    419,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_241.png": [
    613,
    328,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_242.png": [
    637,
    290,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_243.png": [
    651,
    254,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_261.png": [
    668,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_263.png": [
    694,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_268.png": [
    698,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_288.png": [
    711,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_289.png": [
    711,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_290.png": [
    736,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_291.png": [
    736,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_292.png": [
    575,
    491,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_293.png": [
    575,
    527,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_301.png": [
    575,
    563,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_31.png": [
    575,
    599,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_32.png": [
    995,
    324,
    29,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_338.png": [
    611,
    455,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_339.png": [
    643,
    364,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_340.png": [
    649,
    326,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_341.png": [
    673,
    290,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_342.png": [
    687,
    254,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_343.png": [
    704,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_379.png": [
    194,
    593,
    21,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_38.png": [
    1028,
    324,
    32,
    29
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_380.png": [
    730,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_381.png": [
    734,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_382.png": [
    643,
    400,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_388.png": [
    747,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_389.png": [
    747,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_39.png": [
    772,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_390.png": [
    772,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_391.png": [
    611,
    491,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_392.png": [
    427,
    502,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_393.png": [
    611,
    527,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_40.png": [
    431,
    610,
    32,
    28
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_402.png": [
    529,
    311,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_403.png": [
    543,
    275,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_404.png": [
    611,
    563,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_405.png": [
    611,
    599,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_41.png": [
    925,
    425,
    32,
    24
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_42.png": [
    683,
    614,
    32,
    24
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_43.png": [
    255,
    610,
    32,
    28
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_438.png": [
    458,
    76,
    32,
    12
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_439.png": [
    1041,
    462,
    32,
    12
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_440.png": [
    1041,
    478,
    32,
    12
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_441.png": [
    945,
    468,
    32,
    12
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_442.png": [
    1005,
    462,
    32,
    13
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_443.png": [
    1017,
    494,
    32,
    11
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_492.png": [
    827,
    613,
    24,
    23
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_493.png": [
    291,
    610,
    32,
    28
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_539.png": [
    1028,
    357,
    32,
    29
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_543.png": [
    647,
    436,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_549.png": [
    955,
    360,
    29,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_550.png": [
    679,
    362,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_563.png": [
    685,
    326,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_580.png": [
    1058,
    146,
    28,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_587.png": [
    709,
    290,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_589.png": [
    723,
    254,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_590.png": [
    740,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_592.png": [
    766,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_593.png": [
    770,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_599.png": [
    1021,
    390,
    28,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_600.png": [
    679,
    398,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_636.png": [
    783,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_637.png": [
    783,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_643.png": [
    808,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_80.png": [
    808,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_832.png": [
    647,
    472,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_833.png": [
    951,
    610,
    17,
    18
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_847.png": [
    647,
    508,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_848.png": [
    647,
    544,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_849.png": [
    647,
    580,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_88.png": [
    683,
    434,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_880.png": [
    637,
    290,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_881.png": [
    715,
    362,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_882.png": [
    1060,
    2,
    26,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_89.png": [
    721,
    326,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_897.png": [
    1060,
    38,
    26,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_898.png": [
    745,
    290,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_899.png": [
    759,
    254,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_90.png": [
    776,
    218,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_91.png": [
    802,
    182,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_92.png": [
    806,
    146,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_93.png": [
    715,
    398,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_930.png": [
    575,
    491,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_931.png": [
    819,
    74,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_932.png": [
    819,
    110,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_946.png": [
    882,
    633,
    5,
    5
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_947.png": [
    844,
    2,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_948.png": [
    844,
    38,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_949.png": [
    683,
    470,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_980.png": [
    683,
    506,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_981.png": [
    683,
    542,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_982.png": [
    683,
    578,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_983.png": [
    876,
    506,
    18,
    31
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_996.png": [
    898,
    506,
    18,
    31
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_997.png": [
    719,
    434,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_998.png": [
    751,
    362,
    32,
    32
  ],
  "assets/fiorwoods-runtime/Sprite_Fiorwoods_999.png": [
    757,
    326,
    32,
    32
  ],
  "assets/forest/bush_01.png": [
    379,
    466,
    44,
    46
  ],
  "assets/forest/bush_02.png": [
    348,
    285,
    76,
    62
  ],
  "assets/forest/bush_03.png": [
    907,
    590,
    20,
    20
  ],
  "assets/forest/bush_04.png": [
    402,
    239,
    48,
    40
  ],
  "assets/forest/fior_canopy_0.png": [
    781,
    290,
    32,
    32
  ],
  "assets/forest/fior_canopy_1.png": [
    721,
    326,
    32,
    32
  ],
  "assets/forest/fior_canopy_2.png": [
    795,
    254,
    32,
    32
  ],
  "assets/forest/fior_canopy_3.png": [
    812,
    218,
    32,
    32
  ],
  "assets/forest/fior_canopy_4.png": [
    838,
    182,
    32,
    32
  ],
  "assets/forest/fior_canopy_5.png": [
    675,
    74,
    32,
    32
  ],
  "assets/forest/fior_canopy_6.png": [
    700,
    2,
    32,
    32
  ],
  "assets/forest/fior_canopy_7.png": [
    842,
    146,
    32,
    32
  ],
  "assets/forest/fior_grass_0.png": [
    751,
    398,
    32,
    32
  ],
  "assets/forest/fior_grass_1.png": [
    855,
    74,
    32,
    32
  ],
  "assets/forest/fior_grass_2.png": [
    855,
    110,
    32,
    32
  ],
  "assets/forest/fior_grass_3.png": [
    880,
    2,
    32,
    32
  ],
  "assets/forest/fior_ground_0.png": [
    880,
    2,
    32,
    32
  ],
  "assets/forest/fior_ground_1.png": [
    880,
    38,
    32,
    32
  ],
  "assets/forest/fior_ground_2.png": [
    719,
    470,
    32,
    32
  ],
  "assets/forest/fior_ground_3.png": [
    719,
    506,
    32,
    32
  ],
  "assets/forest/path_center.png": [
    933,
    567,
    16,
    16
  ],
  "assets/forest/path_e.png": [
    952,
    587,
    16,
    16
  ],
  "assets/forest/path_n.png": [
    953,
    565,
    16,
    16
  ],
  "assets/forest/path_ne.png": [
    972,
    585,
    16,
    16
  ],
  "assets/forest/path_nw.png": [
    973,
    565,
    16,
    16
  ],
  "assets/forest/path_plain_alt.png": [
    972,
    605,
    16,
    16
  ],
  "assets/forest/path_s.png": [
    992,
    585,
    16,
    16
  ],
  "assets/forest/path_se.png": [
    993,
    555,
    16,
    16
  ],
  "assets/forest/path_sw.png": [
    992,
    605,
    16,
    16
  ],
  "assets/forest/path_w.png": [
    1012,
    575,
    16,
    16
  ],
  "assets/forest/tree_primary_02.png": [
    2,
    138,
    164,
    214
  ],
  "assets/forest/tree_primary_03.png": [
    170,
    138,
    174,
    210
  ],
  "assets/forest/tree_shadow.png": [
    379,
    412,
    50,
    50
  ],
  "assets/forest/tree_small_04.png": [
    446,
    92,
    45,
    71
  ],
  "assets/forest/tree_small_05.png": [
    348,
    203,
    50,
    78
  ],
  "assets/forest/tree_small_06.png": [
    294,
    2,
    76,
    98
  ],
  "assets/gates.png": [
    405,
    351,
    48,
    48
  ],
  "assets/oak-tree.png": [
    374,
    2,
    80,
    86
  ],
  "assets/plate_spritesheet.png": [
    402,
    203,
    72,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_108.png": [
    719,
    542,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_11.png": [
    719,
    578,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_112.png": [
    916,
    2,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_157.png": [
    1071,
    74,
    15,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_163.png": [
    827,
    506,
    16,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_207.png": [
    1069,
    290,
    15,
    26
  ],
  "assets/portal-platform/Sprite_Tormund_213.png": [
    1064,
    360,
    16,
    26
  ],
  "assets/portal-platform/Sprite_Tormund_258.png": [
    952,
    2,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_262.png": [
    988,
    2,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_3.png": [
    1024,
    2,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_308.png": [
    433,
    439,
    26,
    18
  ],
  "assets/portal-platform/Sprite_Tormund_310.png": [
    467,
    619,
    32,
    18
  ],
  "assets/portal-platform/Sprite_Tormund_311.png": [
    647,
    616,
    32,
    18
  ],
  "assets/portal-platform/Sprite_Tormund_312.png": [
    469,
    407,
    26,
    18
  ],
  "assets/portal-platform/Sprite_Tormund_56.png": [
    916,
    38,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_58.png": [
    952,
    38,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_8.png": [
    988,
    38,
    32,
    32
  ],
  "assets/portal-platform/Sprite_Tormund_9.png": [
    1024,
    38,
    32,
    32
  ],
  "assets/portal_spritesheet.png": [
    2,
    2,
    288,
    96
  ],
  "assets/runestones.png": [
    255,
    352,
    96,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1001.png": [
    891,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1002.png": [
    719,
    614,
    32,
    14
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1003.png": [
    495,
    148,
    18,
    14
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1004.png": [
    884,
    590,
    18,
    14
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1005.png": [
    927,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_105.png": [
    446,
    167,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_106.png": [
    478,
    203,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_108.png": [
    395,
    566,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_109.png": [
    395,
    602,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_110.png": [
    495,
    76,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1101.png": [
    961,
    432,
    18,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1153.png": [
    963,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_1203.png": [
    999,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_154.png": [
    1035,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_155.png": [
    891,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_156.png": [
    927,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_157.png": [
    963,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_204.png": [
    999,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_205.png": [
    1035,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/AncientRuins/Sprite_Ancient Ruins_207.png": [
    755,
    434,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_102.png": [
    433,
    403,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_105.png": [
    531,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1103.png": [
    431,
    538,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1107.png": [
    787,
    362,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1108.png": [
    793,
    326,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1109.png": [
    469,
    371,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1110.png": [
    493,
    316,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1112.png": [
    524,
    239,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1113.png": [
    817,
    290,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1114.png": [
    550,
    184,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1152.png": [
    554,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1153.png": [
    831,
    254,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1156.png": [
    592,
    2,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1158.png": [
    592,
    38,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1159.png": [
    467,
    511,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1161.png": [
    467,
    547,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1162.png": [
    467,
    583,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1164.png": [
    499,
    407,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1202.png": [
    529,
    311,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1203.png": [
    543,
    275,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1204.png": [
    611,
    563,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1205.png": [
    611,
    599,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1207.png": [
    586,
    182,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1208.png": [
    848,
    218,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1210.png": [
    499,
    443,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1211.png": [
    603,
    74,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1212.png": [
    603,
    110,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1213.png": [
    628,
    2,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1433.png": [
    925,
    396,
    32,
    25
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1434.png": [
    859,
    391,
    32,
    26
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1443.png": [
    865,
    361,
    32,
    26
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1482.png": [
    895,
    427,
    24,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1485.png": [
    503,
    515,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1495.png": [
    874,
    182,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1498.png": [
    990,
    396,
    24,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1532.png": [
    856,
    450,
    24,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1537.png": [
    579,
    292,
    18,
    15
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1548.png": [
    827,
    470,
    24,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1582.png": [
    827,
    434,
    25,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1587.png": [
    571,
    383,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1588.png": [
    981,
    479,
    32,
    12
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1590.png": [
    755,
    614,
    32,
    14
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1591.png": [
    791,
    614,
    32,
    13
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1598.png": [
    961,
    396,
    25,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1637.png": [
    878,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1638.png": [
    787,
    398,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1640.png": [
    755,
    470,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1641.png": [
    755,
    506,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1736.png": [
    457,
    371,
    8,
    28
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1786.png": [
    1064,
    324,
    21,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1888.png": [
    755,
    542,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1890.png": [
    755,
    578,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1891.png": [
    914,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1981.png": [
    884,
    569,
    21,
    17
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_1987.png": [
    539,
    532,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_2037.png": [
    950,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_2038.png": [
    986,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_2039.png": [
    1022,
    146,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_2040.png": [
    910,
    182,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_404.png": [
    611,
    563,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_405.png": [
    611,
    599,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Fiorwoods/Sprite_Fiorwoods_563.png": [
    685,
    326,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_112.png": [
    1071,
    110,
    10,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_158.png": [
    855,
    486,
    17,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_159.png": [
    946,
    182,
    32,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_160.png": [
    889,
    290,
    32,
    31
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_64.png": [
    988,
    360,
    29,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_65.png": [
    865,
    326,
    20,
    31
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_67.png": [
    983,
    432,
    18,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_68.png": [
    923,
    453,
    18,
    32
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_70.png": [
    953,
    499,
    20,
    31
  ],
  "assets/runtime-style/Assets/Maps/Village/Sprite_Village_71.png": [
    920,
    499,
    29,
    31
  ],
  "assets/runtime-style/Assets/Prefabs/World/Natural Decoration/grave1.png": [
    827,
    555,
    27,
    27
  ],
  "assets/runtime-style/Assets/Prefabs/World/Natural Decoration/roots01 #2196988.png": [
    2,
    519,
    175,
    113
  ],
  "assets/runtime-style/Assets/Prefabs/World/Natural Decoration/roots02.png": [
    2,
    356,
    213,
    159
  ],
  "assets/runtime-style/Assets/Prefabs/World/Natural Decoration/roots04.png": [
    348,
    104,
    94,
    95
  ],
  "assets/runtime-style/Assets/Prefabs/World/Natural Decoration/roots05 #2196401.png": [
    428,
    283,
    39,
    48
  ],
  "assets/runtime-style/Assets/Sprites/World/Natural Objects/watergrass_6.png": [
    827,
    586,
    25,
    23
  ],
  "assets/runtime-style/ancientPillar.png": [
    219,
    352,
    32,
    133
  ],
  "assets/runtime-style/ancientPillarBroken.png": [
    219,
    489,
    32,
    133
  ],
  "assets/runtime-style/plateActivated.png": [
    982,
    182,
    32,
    32
  ],
  "assets/runtime-style/plateDeactivated.png": [
    1018,
    182,
    32,
    32
  ],
  "assets/runtime-style/statuePillars_blue 10.png": [
    181,
    519,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_blue 11.png": [
    458,
    2,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_blue 12.png": [
    489,
    2,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_blue 13.png": [
    255,
    388,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_blue 6.png": [
    255,
    462,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_red 10.png": [
    255,
    536,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_red 11.png": [
    286,
    388,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_red 12.png": [
    286,
    462,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_red 13.png": [
    286,
    536,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_red 6.png": [
    317,
    388,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_yellow 10.png": [
    317,
    462,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_yellow 11.png": [
    317,
    536,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_yellow 12.png": [
    348,
    388,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_yellow 13.png": [
    348,
    462,
    27,
    70
  ],
  "assets/runtime-style/statuePillars_yellow 6.png": [
    348,
    536,
    27,
    70
  ],
  "assets/runtime-style/sword03.png": [
    379,
    351,
    22,
    57
  ],
  "assets/runtime-style/sword04.png": [
    379,
    566,
    12,
    46
  ],
  "assets/runtime-style/sword05.png": [
    181,
    593,
    9,
    44
  ],
  "assets/shadow_corner.png": [
    1013,
    541,
    16,
    16
  ],
  "assets/shadow_left.png": [
    1012,
    595,
    16,
    16
  ],
  "assets/shadow_top.png": [
    1012,
    615,
    16,
    16
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_100.png": [
    363,
    616,
    25,
    17
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1115.png": [
    1054,
    182,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1118.png": [
    884,
    218,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1119.png": [
    920,
    218,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1120.png": [
    956,
    218,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1121.png": [
    992,
    218,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1125.png": [
    1028,
    218,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1126.png": [
    791,
    434,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1127.png": [
    823,
    362,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1165.png": [
    829,
    326,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1166.png": [
    853,
    290,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1167.png": [
    867,
    254,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1172.png": [
    823,
    398,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1175.png": [
    791,
    470,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1177.png": [
    791,
    506,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1220.png": [
    791,
    542,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1221.png": [
    791,
    578,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_1222.png": [
    903,
    254,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_48.png": [
    1053,
    390,
    27,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_49.png": [
    961,
    324,
    30,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_563.png": [
    685,
    326,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_9.png": [
    556,
    2,
    32,
    32
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_98.png": [
    876,
    541,
    29,
    24
  ],
  "assets/swamp-obstacle/Sprite_Rohlan_Fields_99.png": [
    1012,
    509,
    30,
    28
  ],
  "assets/swamp-obstacle/watergrass_0.png": [
    895,
    391,
    26,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_154.png": [
    1035,
    74,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_156.png": [
    927,
    110,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_157.png": [
    963,
    110,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_204.png": [
    999,
    110,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_205.png": [
    1035,
    110,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_206.png": [
    939,
    254,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_207.png": [
    755,
    434,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Ancient_Ruins_208.png": [
    884,
    463,
    32,
    18
  ],
  "assets/t-intersection-decoration/Sprite_Rohlan_Fields_350.png": [
    518,
    184,
    28,
    15
  ],
  "assets/t-intersection-decoration/Sprite_Rohlan_Fields_399.png": [
    925,
    290,
    32,
    31
  ],
  "assets/t-intersection-decoration/Sprite_Rohlan_Fields_400.png": [
    975,
    254,
    32,
    32
  ],
  "assets/t-intersection-decoration/Sprite_Rohlan_Fields_450.png": [
    1064,
    218,
    22,
    32
  ],
  "assets/t-intersection-decoration/bush01.png": [
    379,
    516,
    44,
    46
  ],
  "assets/t-intersection-decoration/bush04.png": [
    402,
    239,
    48,
    40
  ],
  "assets/t-intersection-decoration/goldflowers_3.png": [
    855,
    613,
    23,
    24
  ],
  "assets/t-intersection-decoration/goldflowers_9.png": [
    977,
    509,
    31,
    13
  ],
  "assets/tiles.png": [
    2,
    102,
    272,
    32
  ],
  "assets/wall_tiles.png": [
    278,
    104,
    64,
    16
  ],
  "assets/wisdom_orb.png": [
    1033,
    541,
    16,
    16
  ]
} as const satisfies Readonly<
  Record<string, readonly [x: number, y: number, width: number, height: number]>
>;
