// Generated by the central-hub style importer.
// Coordinates are authoring pixels relative to the 30x30 hub's north-west tile.

export type CentralHubColliderSpec = readonly [
  x: number,
  y: number,
  width: number,
  height: number,
  rightTriangle: 0 | 1,
  flipX: 0 | 1,
  flipY: 0 | 1,
];

export interface CentralHubRunestoneSpec {
  readonly index: number;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export const CENTRAL_HUB_COLLIDER_SPECS: readonly CentralHubColliderSpec[] = [
  [196, 211, 8, 6, 0, 0, 0],
  [236, 252, 8, 6, 0, 0, 0],
  [277, 211, 8, 6, 0, 0, 0],
  [152, 175, 16, 16, 0, 0, 0],
  [152, 269, 16, 16, 0, 0, 0],
  [312, 175, 16, 16, 0, 0, 0],
  [314, 268, 16, 16, 0, 0, 0],
  [-16, 251, 16, 16, 0, 0, 0],
  [198, 476, 16, 16, 0, 0, 0],
  [481, 249, 16, 16, 0, 0, 0],
  [17, 16, 127, 185, 0, 0, 0],
  [146, 16, 62, 155, 0, 0, 0],
  [273, 16, 62, 155, 0, 0, 0],
  [336, 17, 127, 185, 0, 0, 0],
  [337, 258, 127, 189, 0, 0, 0],
  [272, 448, 177, 14, 0, 0, 0],
  [272, 289, 65, 158, 0, 0, 0],
  [450, 448, 13, 12, 1, 0, 1],
  [144, 289, 65, 158, 0, 0, 0],
  [32, 447, 177, 14, 0, 0, 0],
  [18, 447, 13, 12, 1, 1, 1],
  [17, 258, 126, 188, 0, 0, 0],
  [199, -6, 16, 16, 0, 0, 0],
];

export const CENTRAL_HUB_RUNESTONE_SPECS: readonly CentralHubRunestoneSpec[] = [
  {
    index: 0,
    x: 192,
    y: 191,
    width: 16,
    height: 32,
  },
  {
    index: 1,
    x: 232,
    y: 231,
    width: 16,
    height: 32,
  },
  {
    index: 2,
    x: 273,
    y: 191,
    width: 16,
    height: 32,
  },
];
